name: Build project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.archconfig }}", gcc, lite ]

    strategy:
      matrix:
        archconfig: [ x86_64, aarch64, armv7l ]
        build_type: [Debug, Release]
      fail-fast: false

    steps:
    - name: Cleanup pervious jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Find SHA
      run: |
        if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
        then
          echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.sha}})" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$(echo ${{ github.head_ref || github.ref_name }})" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "ARTIFACT_SHA=$(echo ${{github.sha}})" >> $GITHUB_ENV
        fi

    - name: Build project
      id: build_vaccelrt
      run: |
        mkdir -p build_${{matrix.build_type}}
        cd build_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DENABLE_TESTS=ON \
          -DBUILD_EXAMPLES=ON && \
        cmake --build . --config ${{matrix.build_type}} && \
        make test && \
        make install -C src && \
        make install -C third-party && \
        make install -C examples

    - name: Build vAccel plugins
      id: build_plugins
      run: |
        cd build_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt \
          -DBUILD_PLUGIN_NOOP=ON && \
        make -C plugins && make install -C plugins

    - name: Run examples
      id: run_examples
      env:
        LD_LIBRARY_PATH: ${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib
        VACCEL_BACKENDS: ${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib/libvaccel-noop.so
        VACCEL_DEBUG_LEVEL: 4
      run: |
        cd ${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt
        sudo mkdir -p /run/user/1001
        sudo chown -R runner /run/user/1001
        ./bin/classify share/images/example.jpg 1
        ./bin/classify_generic share/images/example.jpg 1
        ./bin/detect share/images/example.jpg 1
        ./bin/detect_generic share/images/example.jpg 1
        ./bin/pose share/images/example.jpg 1
        ./bin/pose_generic share/images/example.jpg 1
        ./bin/segment share/images/example.jpg 1
        ./bin/segment_generic share/images/example.jpg 1
        ./bin/depth share/images/example.jpg 1
        ./bin/depth_generic share/images/example.jpg 1
        ./bin/sgemm
        ./bin/sgemm_generic
        ./bin/minmax 262144 ./share/input/input_262144.csv 5 100
        ./bin/minmax_generic 262144 ./share/input/input_262144.csv 5 100
        ./bin/pynq_vector_add
        ./bin/pynq_array_copy
        ./bin/pynq_parallel
        ./bin/torch_inference ./share/images/example.jpg ./share/models/torch

    - name: Upload binary distr to s3
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: artifacts/${{ matrix.archconfig }}/${{ matrix.build_type }}/opt
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_SHA }}/${{ matrix.archconfig }}/${{ matrix.build_type }}/

    - name: Build project for packages
      id: build_pkg_vaccelrt
      run: |
        mkdir -p build_pkg_${{matrix.build_type}}
        cd build_pkg_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DBUILD_EXAMPLES=ON \
          -DBUILD_PLUGIN_NOOP=ON \
          -DBUILD_PLUGIN_EXEC=ON && \
        cmake --build . --config ${{matrix.build_type}} && \
        cpack -G TGZ
        cpack 

    - name: Get package name
      shell: bash
      id: get_package_deb
      run: |
        echo ::set-output name=NAME::$(basename build_pkg_${{ matrix.build_type }}/vaccel-*.deb)

    - name: Get tar name
      shell: bash
      id: get_package_tar
      run: |
        echo ::set-output name=NAME::$(basename build_pkg_${{ matrix.build_type }}/vaccel-*.tar.gz)

    - name: Upload deb artifact to s3 by name
      uses: cloudkernels/minio-upload@v4
      if: ${{ env.ARTIFACT_NAME != 'master' }}
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: build_pkg_${{ matrix.build_type }}/${{ steps.get_package_deb.outputs.NAME }}
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_NAME }}/${{ matrix.archconfig }}/${{ matrix.build_type }}-deb/
        policy: 1

    - name: Upload deb artifact to s3
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: build_pkg_${{ matrix.build_type }}/${{ steps.get_package_deb.outputs.NAME }}
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_SHA }}/${{ matrix.archconfig }}/${{ matrix.build_type }}-deb/
        policy: 1

    - name: Upload tar artifact to s3 by name
      uses: cloudkernels/minio-upload@v4
      if: ${{ env.ARTIFACT_NAME != 'master' }}
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: build_pkg_${{ matrix.build_type }}/${{ steps.get_package_tar.outputs.NAME }}
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_NAME }}/${{ matrix.archconfig }}/${{ matrix.build_type }}-tar/
        policy: 1

    - name: Upload tar artifact to s3
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: build_pkg_${{ matrix.build_type }}/${{ steps.get_package_tar.outputs.NAME }}
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_SHA }}/${{ matrix.archconfig }}/${{ matrix.build_type }}-tar/
        policy: 1

    - name: Clean-up
      run: sudo rm -rf artifacts build_${{ matrix.build_type }}
